spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    driver-class-name: org.postgresql.Driver
  freemarker:
    template-loader-path: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update