
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:db_design_to_xlsx
    driver-class-name: org.h2.Driver
  freemarker:
    template-loader-path: classpath:/templates/
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8989